---
- name: Wait for cloud init to finish
  hosts: all
  tasks:
  - cloud_init_data_facts:
      filter: status
    register: res
    until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
    retries: 60
    delay: 5
    failed_when: res.cloud_init_data_facts.result.v1.errors is defined and (res.cloud_init_data_facts.result.v1.errors | length > 0)